import "@/app/css/reset.css";
import "@/app/css/style.css";
import "@/app/css/style.scss";

export const metadata = {
  title: "ZARADA",
  description: "Generated by twgu",
  icons: { icon: "/images/hdpi.png" },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className="app-template default">{children}</div>
      </body>
    </html>
  );
}
